export const VISUAL_CROSSING = {
  BASE_URL: process.env.NEXT_PUBLIC_VISUAL_CROSSING_API_URL,
  API_KEY: process.env.NEXT_PUBLIC_VISUAL_CROSSING_API_KEY,
};
export const BLYNK = {
  BASE_URL: process.env.NEXT_PUBLIC_BLYNK_API_URL,
  BLYNK_TOKEN: process.env.NEXT_PUBLIC_BLYNK_DEVICE_TOKEN,
};
