export const metadata = [
  {
    id: 1,
    name: "r1 mode",
    pin: "v0",
    color: "#FF6B6B",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 2,
    name: "r1 light",
    pin: "v1",
    color: "#FFD93D",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 3,
    name: "r1 fan",
    pin: "v2",
    color: "#6BCB77",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 4,
    name: "r2 mode",
    pin: "v3",
    color: "#4D96FF",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 5,
    name: "r2 light",
    pin: "v4",
    color: "#845EC2",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 6,
    name: "r2 fan",
    pin: "v5",
    color: "#00C9A7",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 7,
    name: "r2 ac",
    pin: "v6",
    color: "#FF9671",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 8,
    name: "R3 fan",
    pin: "v7",
    color: "#FFC75F",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 9,
    name: "r3 light",
    pin: "v8",
    color: "#F9F871",
    dataType: "Integer",
    units: "N/A",
    isRaw: false,
    min: 0,
    max: 1,
    defaultValue: 0,
    automationType: "Switch",
  },
  {
    id: 10,
    name: "ac voltage",
    pin: "v10",
    color: "#F28B82",
    dataType: "Double",
    units: "v",
    isRaw: false,
    min: 0,
    max: 300,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 11,
    name: "AC Ampere",
    pin: "v11",
    color: "#A7FFEB",
    dataType: "Double",
    units: "A",
    isRaw: false,
    min: 0,
    max: 30,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 12,
    name: "AC Power",
    pin: "v12",
    color: "#FFD700",
    dataType: "Double",
    units: "W",
    isRaw: false,
    min: 0,
    max: 5000,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 13,
    name: "AC Fre",
    pin: "v13",
    color: "#C084FC",
    dataType: "Double",
    units: "Hz",
    isRaw: false,
    min: 45,
    max: 50,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 14,
    name: "Dc Voltage",
    pin: "v14",
    color: "#7DD3FC",
    dataType: "Double",
    units: "V",
    isRaw: true,
    min: 0,
    max: 50,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 15,
    name: "DC AMP",
    pin: "v15",
    color: "#D65DB1",
    dataType: "Double",
    units: "A",
    isRaw: false,
    min: 0,
    max: 5,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 16,
    name: "temp",
    pin: "v16",
    color: "#F87171",
    dataType: "Double",
    units: "°C",
    isRaw: false,
    min: 0,
    max: 100,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 18,
    name: "pir led",
    pin: "v18",
    color: "#FF6F91",
    dataType: "Integer",
    units: "",
    isRaw: false,
    min: 0,
    max: 1,
    decimals: "--",
    defaultValue: "0",
    automationType: "Switch",
  },
  {
    id: 19,
    name: "kwh",
    pin: "v19",
    color: "#00B8A9",
    dataType: "Double",
    units: "kWh",
    isRaw: false,
    min: 0,
    max: 9999,
    decimals: "#.##",
    defaultValue: "",
    automationType: "Sensor",
  },
  {
    id: 20,
    name: "Integer V9",
    pin: "v20",
    color: "#B39CD0",
    dataType: "Integer",
    units: "",
    isRaw: false,
    min: 0,
    max: 1,
    decimals: "--",
    defaultValue: "0",
    automationType: "Sensor",
  },
  {
    id: 21,
    name: "Digital Pin 10",
    pin: "10",
    color: "#FF8066",
    dataType: "Integer",
    units: "",
    isRaw: false,
    min: 0,
    max: 1,
    decimals: "--",
    defaultValue: "0",
    automationType: "",
  },
];